code --install-extension 42Crunch.vscode-openapi
code --install-extension AdamCaviness.theme-monokai-dark-soda
code --install-extension adelphes.android-dev-ext
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension AndreyVolosovich.monokai-st3
code --install-extension apollographql.vscode-apollo
code --install-extension blaxk.serverless-command
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cschleiden.vscode-github-actions
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dcasella.monokai-plusplus
code --install-extension DiemasMichiels.emulate
code --install-extension doi.fileheadercomment
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension erd0s.terraform-autocomplete
code --install-extension eriklynd.json-tools
code --install-extension formulahendry.github-actions
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension gerane.Theme-Monokai
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GoldenMaximo.monokai-maximo
code --install-extension GoliafRS.monokai-grs
code --install-extension jaszhix.theme-monokaiMega
code --install-extension jhartell.vscode-line-endings
code --install-extension KnisterPeter.vscode-github
code --install-extension konapun.monokaiju
code --install-extension LaurentTreguier.monokai-grey
code --install-extension lunaryorn.fish-ide
code --install-extension mauve.terraform
code --install-extension maximetinu.identical-sublime-monokai-csharp-theme-colorizer
code --install-extension me-dutour-mathieu.vscode-github-actions
code --install-extension mechatroner.rainbow-csv
code --install-extension mermade.openapi-lint
code --install-extension mikestead.dotenv
code --install-extension mohsen1.prettify-json
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.powershell
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mushan.vscode-open-iterm2
code --install-extension nachocab.run-external
code --install-extension nonylene.dark-molokai-theme
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension possan.nbsp-vscode
code --install-extension psioniq.psi-header
code --install-extension qub.qub-xml-vscode
code --install-extension redhat.vscode-yaml
code --install-extension Scatolina.theme-monokaiextended
code --install-extension skyapps.fish-vscode
code --install-extension TheNightmanCodeth.licensesnippets
code --install-extension vscoss.vscode-ansible
code --install-extension ymotongpoo.licenser
code --install-extension yzhang.markdown-all-in-one
